# Generated by Django 2.2 on 2020-07-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('ifsc_code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
