# Generated by Django 2.2 on 2020-07-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='owner',
        ),
    ]
